'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrthographicCamera,Instances,Instance} from '@react-three/drei';
import {useRef} from 'react';
import type {Group} from 'three';
import type {ShelterCat} from '@/lib/data/shelter';
import {FlatShelter} from './flat-shelter';
type Point=[number,number,number];
const walls:{position:Point;scale:Point;color:string}[]=[{position:[0,-.15,0],scale:[7,.3,5],color:'#cbae89'},{position:[0,1.55,-2.5],scale:[7,3.4,.15],color:'#f4e4d0'},{position:[-3.5,1.55,0],scale:[.15,3.4,5],color:'#e8d0b4'},{position:[.6,2,-2.38],scale:[2,1.65,.08],color:'#abc4b6'},{position:[.6,2,-2.29],scale:[.08,1.8,.12],color:'#fff3d9'},{position:[.6,2,-2.29],scale:[2.15,.08,.12],color:'#fff3d9'},{position:[.6,1.13,-2.22],scale:[2.25,.13,.35],color:'#fff3d9'},{position:[.6,2.86,-2.29],scale:[2.2,.12,.12],color:'#fff3d9'},{position:[-.48,2,-2.29],scale:[.12,1.8,.12],color:'#fff3d9'},{position:[1.68,2,-2.29],scale:[.12,1.8,.12],color:'#fff3d9'},{position:[-2.5,.25,-1.5],scale:[.9,.5,.8],color:'#c3926e'}];
function Cat({cat,index,onCat}:{cat:ShelterCat;index:number;onCat:(cat:ShelterCat)=>void}){const ref=useRef<Group>(null);const tail=useRef<Group>(null);const eyes=useRef<Group>(null);const destination=useRef(0);useFrame(({clock},delta)=>{if(!ref.current)return;const t=clock.elapsedTime+index*2;const playful=cat.personality==='juguetón';const sleeping=cat.personality==='dormilón';ref.current.position.y=.08+Math.sin(t*1.8)*.013;ref.current.scale.y=1+Math.sin(t*1.8)*.025;if(destination.current!==0){ref.current.position.z+=(destination.current-ref.current.position.z)*Math.min(delta*2,1)}else if(!sleeping){ref.current.position.x=index*.75-1+Math.sin(t*(playful?.55:.15))*.35}if(tail.current)tail.current.rotation.z=Math.sin(t*(playful?3:1.2))*.22;if(eyes.current)eyes.current.scale.y=sleeping?.12:t%5>.13?1:.08});return <group ref={ref} position={[index*.75-1,.08,.3+(index%2)*.8]} scale={.7} onClick={e=>{e.stopPropagation();destination.current=cat.personality==='tímido'?-1:1.6;onCat(cat)}}><Instances limit={5}><sphereGeometry args={[1,12,8]}/><meshStandardMaterial color={cat.palette.body}/><Instance position={[0,.45,0]} scale={[.38,.43,.55]}/><Instance position={[0,.85,.32]} scale={[.43,.36,.35]}/><Instance position={[-.23,.13,.27]} scale={[.15,.13,.26]}/><Instance position={[.23,.13,.27]} scale={[.15,.13,.26]}/><Instance position={[0,.2,-.25]} scale={[.35,.2,.32]}/></Instances><Instances limit={2}><coneGeometry args={[.19,.36,4]}/><meshStandardMaterial color={cat.palette.body}/><Instance position={[-.25,1.16,.3]} rotation={[0,0,.2]}/><Instance position={[.25,1.16,.3]} rotation={[0,0,-.2]}/></Instances><group ref={tail} position={[0,.35,-.45]}><Instances limit={3}><cylinderGeometry args={[.07,.08,.32,7]}/><meshStandardMaterial color={cat.palette.body}/><Instance position={[0,.12,-.08]} rotation={[-.6,0,0]}/><Instance position={[0,.39,-.19]} rotation={[-.2,0,0]}/><Instance position={[0,.67,-.2]} rotation={[.2,0,0]}/></Instances></group><Instances limit={2}><sphereGeometry args={[1,10,6]}/><meshStandardMaterial color={cat.palette.belly}/><Instance position={[0,.38,.47]} scale={[.26,.29,.06]}/><Instance position={[0,.74,.63]} scale={[.2,.12,.045]}/></Instances><group ref={eyes} position={[0,.9,.635]}><Instances limit={2}><sphereGeometry args={[1,8,6]}/><meshBasicMaterial color="#35403d"/><Instance position={[-.16,0,0]} scale={[.045,.07,.025]}/><Instance position={[.16,0,0]} scale={[.045,.07,.025]}/></Instances></group></group>}
export default function Room({cats,onCat}:{cats:ShelterCat[];onCat:(cat:ShelterCat)=>void}){return <Canvas dpr={[1,1.5]} gl={{antialias:false,powerPreference:'low-power'}} fallback={<FlatShelter cats={cats} onCat={onCat}/>}><OrthographicCamera makeDefault position={[7,6,9]} zoom={58} onUpdate={camera=>camera.lookAt(0,1,0)}/><ambientLight intensity={1.5}/><directionalLight position={[3,6,4]} intensity={2} color="#fff1d2"/><Instances limit={walls.length}><boxGeometry/><meshStandardMaterial roughness={1}/>{walls.map((w,i)=><Instance key={i} {...w}/>)}</Instances><mesh rotation={[-Math.PI/2,0,0]} position={[0,.02,.3]} scale={[2.1,1.4,1]}><circleGeometry args={[1,40]}/><meshBasicMaterial color="#98ab91"/></mesh><Instances limit={6}><circleGeometry args={[.45,16]}/><meshBasicMaterial color="#4a5859" transparent opacity={.13}/>{cats.map((c,i)=><Instance key={c.id} rotation={[-Math.PI/2,0,0]} position={[i*.75-1,.035,.3+(i%2)*.8]} scale={[1,.7,1]}/>)}</Instances>{cats.map((cat,index)=><Cat key={cat.id} cat={cat} index={index} onCat={onCat}/>)}</Canvas>}
