'use client';
import {useEffect,useState} from 'react';
import {QuestionPreview} from './question-preview';
import {validateDriveBank} from '@/lib/engine/drive-bank';
import type {CustomQuestion} from '@/lib/engine/types';
type DriveFile={id:string;name:string;size:string;modifiedTime:string};
type Status={configured:boolean;oauthReady?:boolean;needsFolder?:boolean;folderName?:string;folder?:string;files?:DriveFile[]};
type Draft={name:string;fileId:string;modifiedTime:string;questions:CustomQuestion[];issues:string[]};
export function DriveLibrary(){
 const [status,setStatus]=useState<Status|null>(null),[folder,setFolder]=useState(''),[busy,setBusy]=useState('Consultando Drive…'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[reviewed,setReviewed]=useState(false),[subject,setSubject]=useState('fisica');
 async function refresh(){setBusy('Consultando Drive…');setError('');try{const response=await fetch('/api/tutor/drive');const data=await response.json();if(!response.ok)throw new Error(data.error);setStatus(data);}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir Drive.');}finally{setBusy('');}}
 useEffect(()=>{const controller=new AbortController();fetch('/api/tutor/drive',{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setStatus(data);const result=new URLSearchParams(location.search).get('drive');if(result==='error')setError('Google no completó la conexión. Vuelve a intentarlo.');if(result==='connected')setNotice('Cuenta conectada. Ahora elige la carpeta de preguntas.');}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'No se pudo abrir Drive.');}).finally(()=>{if(!controller.signal.aborted)setBusy('');});return()=>controller.abort();},[]);
 async function connectFolder(){setBusy('Comprobando carpeta…');setError('');try{const response=await fetch('/api/tutor/drive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder})});const data=await response.json();if(!response.ok)throw new Error(data.error);await refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo conectar la carpeta.');}finally{setBusy('');}}
 async function importFile(file:DriveFile){
  setBusy('Leyendo PDF…');setError('');setNotice('');setDraft(null);setReviewed(false);
  let document:import('pdfjs-dist').PDFDocumentProxy|undefined;
  let loading:import('pdfjs-dist').PDFDocumentLoadingTask|undefined;
  try{
   const response=await fetch(`/api/tutor/drive?file=${encodeURIComponent(file.id)}`);if(!response.ok){const data=await response.json();throw new Error(data.error);}
   const lib=await import('pdfjs-dist');lib.GlobalWorkerOptions.workerSrc='/pdf/pdf.worker.min.mjs';
   loading=lib.getDocument({data:await response.arrayBuffer()});document=await loading.promise;
   if(document.numPages>30)throw new Error('Usa un PDF de hasta 30 páginas por microhabilidad.');
   let text='';for(let n=1;n<=document.numPages;n++){const page=await document.getPage(n),content=await page.getTextContent();text+=`\nPágina ${n}\n`+content.items.map(i=>'str' in i?i.str+(i.hasEOL?'\n':' '):'').join('');if(text.length>30000)throw new Error('Este PDF es muy largo. Usa hasta 30.000 caracteres por banco.');}
   setBusy('Organizando las preguntas por nivel…');
   const imported=await fetch('/api/tutor/drive/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileId:file.id,text})});const data=await imported.json();if(!imported.ok)throw new Error(data.error);setDraft(data);setNotice('Revisa el contenido y las respuestas antes de activar.');
  }catch(e){setError(e instanceof Error?e.message:'No pudimos importar el PDF.');}finally{await loading?.destroy();setBusy('');}
 }
 async function publish(){if(!draft)return;setBusy('Guardando banco…');setError('');try{const questions=validateDriveBank(draft.questions);const response=await fetch('/api/tutor/drive/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,questions,subject,action:'publish'})});const data=await response.json();if(!response.ok)throw new Error(data.error);setDraft(null);setNotice(`${draft.name}: banco activado. Las nuevas prácticas diarias usarán tus PDF.`);}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy('');}}
 const update=(index:number,change:Partial<CustomQuestion>)=>{setDraft(d=>d?{...d,questions:d.questions.map((q,i)=>i===index?{...q,...change,hints:change.answer?[q.hints[0],q.hints[1],`La respuesta propuesta por tu profe es: ${change.answer}. Compara con tu razonamiento.`]:q.hints}:q)}:null);setReviewed(false);};
 return <section id="drive" className="drive-library" aria-label="Banco de Google Drive">
  <header><span className="drive-eyebrow">TU MATERIAL, SU PRÁCTICA</span><h2>Una carpeta. Un reto cada día.</h2><p>Un PDF por microhabilidad. Laura recibe 10 preguntas al azar, de fácil a difícil.</p></header>
  <div className="drive-rule"><strong>1 microhabilidad</strong><span>10 preguntas</span><span>4 niveles</span></div>
  {status&&!status.configured&&<div className="drive-connect"><h3>Conecta tu Google Drive</h3><p>La aplicación leerá los PDF de la carpeta que elijas. Tus archivos no se hacen públicos ni se modifican.</p>{status.oauthReady?<a className="primary" href="/api/tutor/drive/connect">Conectar mi cuenta de Google</a>:<p className="drive-setup-note">La conexión de Google aún necesita activación en el servidor. Puedes seguir usando «Crear preguntas → PDF e imágenes» mientras se configura.</p>}<small>Google solicita acceso de lectura a Drive; Refugio limita las importaciones a tu carpeta elegida.</small></div>}
  {status?.configured&&<><div className="drive-folder"><div><h3>{status.folderName||'Elige tu carpeta'}</h3>{status.folder&&<a target="_blank" rel="noreferrer" href={`https://drive.google.com/drive/folders/${status.folder}`}>Abrir en Google Drive ↗</a>}</div><button className="secondary" disabled={Boolean(busy)} onClick={()=>void refresh()}>Actualizar archivos</button></div>
  <details open={status.needsFolder}><summary>{status.needsFolder?'Conectar carpeta':'Cambiar carpeta'}</summary><label>Enlace de la carpeta<input type="url" placeholder="https://drive.google.com/drive/folders/…" value={folder} onChange={e=>setFolder(e.target.value)}/></label><button className="secondary" disabled={Boolean(busy)||!folder.trim()} onClick={()=>void connectFolder()}>Usar esta carpeta</button></details>
  {status.files?.length===0&&!status.needsFolder&&<p>La carpeta está vacía. Añade un PDF por microhabilidad y actualiza los archivos.</p>}
  <div className="drive-files">{status.files?.map(file=><div className="drive-file-row" key={file.id}><span className="drive-pdf-icon">PDF</span><div><strong>{file.name.replace(/\.pdf$/i,'')}</strong><small>{Math.round(Number(file.size)/1024)} KB · actualizado {new Date(file.modifiedTime).toLocaleDateString('es-CO')}</small></div><button className="secondary" disabled={Boolean(busy)} onClick={()=>void importFile(file)}>Importar y revisar</button></div>)}</div></>}
  {busy&&<p role="status" className="drive-working">{busy}</p>}{error&&<div><p role="alert" className="error">{error}</p>{!status&&<button className="secondary" disabled={Boolean(busy)} onClick={()=>void refresh()}>Reintentar conexión</button>}</div>}{notice&&<p role="status" className="success-message">{notice}</p>}
  {draft&&<div className="drive-review"><h3>{draft.name}</h3><p>{draft.questions.length} preguntas extraídas · revisa las respuestas con tu PDF.</p><div className="drive-levels">{[1,2,3,4].map(l=><span key={l}>Nivel {l-1}<strong>{draft.questions.filter(q=>q.level===l).length}</strong></span>)}</div>
   {draft.issues.length>0&&<details open><summary>Observaciones de la importación</summary><ul>{draft.issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul></details>}
   <label>Materia<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="fisica">Física</option><option value="matematicas">Matemáticas</option><option value="quimica">Química</option></select></label>
   {draft.questions.map((q,i)=><details className="drive-review-question" key={i}><summary>{i+1}. {q.prompt.slice(0,100)}<small>Nivel {q.level-1}</small></summary><label>Enunciado<textarea value={q.prompt} onChange={e=>update(i,{prompt:e.target.value})}/></label><label>Nivel<select value={q.level} onChange={e=>update(i,{level:Number(e.target.value) as CustomQuestion['level']})}>{[1,2,3,4].map(l=><option value={l} key={l}>{l-1}</option>)}</select></label><label>Respuesta correcta{q.choices?.length?<select value={q.answer} onChange={e=>update(i,{answer:e.target.value})}>{q.choices.map(c=><option value={c.value} key={c.value}>{c.label}</option>)}</select>:<input value={q.answer} onChange={e=>update(i,{answer:e.target.value})}/>}</label><QuestionPreview key={JSON.stringify(q)} question={q}/><button type="button" className="quiet" onClick={()=>{setDraft({...draft,questions:draft.questions.filter((_,n)=>n!==i)});setReviewed(false);}}>Excluir esta pregunta</button></details>)}
   <label className="drive-reviewed"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Revisé las preguntas, sus niveles y respuestas.</label><button className="primary" disabled={!reviewed||Boolean(busy)} onClick={()=>void publish()}>Activar para las prácticas diarias</button>
  </div>}
  <details className="drive-guide"><summary>Cómo preparar tus PDF</summary><p>Nombra cada archivo con una microhabilidad, por ejemplo «Despejar presión.pdf». Incluye encabezados Nivel 0, 1, 2 y 3 y un solucionario. Mínimo: 3, 3, 2 y 2 preguntas respectivamente; puedes añadir hasta 15 por nivel para tener variedad.</p><p>Se conserva el texto del PDF. Los escaneos y ejercicios que dependen de imágenes se importan manualmente desde Crear preguntas. Cada actualización se revisa antes de sustituir el banco activo.</p></details>
 </section>;
}
