import type {Attempt,Skill} from '@/lib/engine/types';
import type {UsageEvent} from '@/lib/engine/telemetry';
import {weeklyProgress,repeatedProgress} from '@/lib/engine/weekly-progress';
const errors:Record<string,string>={SIGNO_AL_TRANSPONER:'Cambio de signo',OPERACION_INVERSA:'Elegir la operación inversa',ORDEN_OPERACIONES:'Orden de operaciones y paréntesis',FACTOR_INVERTIDO:'Factor o cociente invertido',VARIABLE_SIN_AISLAR:'La letra aún no está sola',FACTOR_LINEAL_EN_AREA:'Conversión de áreas',CONTEO_ATOMOS:'Conteo de átomos',RATIO_NO_MINIMO:'Coeficientes sin simplificar',UNKNOWN:'Respuesta por revisar'};
export function LearningProgress({attempts,skills,today,events}:{attempts:Attempt[];skills:Skill[];today:string;events:UsageEvent[]}){
 const days=weeklyProgress(attempts,today);const hints=events.filter(e=>e.event_name==='hint_requested'&&!e.is_test&&e.actor_kind==='shared_refuge').slice(0,15);
 return <section className="learning-progress"><h2>Esta semana, paso a paso</h2><div className="week-strip">{days.map(day=><div key={day.date}><time>{new Date(day.date+'T12:00:00').toLocaleDateString('es-CO',{weekday:'short',day:'numeric'})}</time><strong>{day.accuracy===null?'—':`${day.accuracy}%`}</strong><span>{day.total?`${day.total} intentos`:'Sin práctica'}</span>{day.maxLevel!==null&&<small>Nivel {day.minLevel} → {day.maxLevel}</small>}</div>)}</div>
 {skills.map(skill=>{const rows=attempts.filter(a=>a.skill_id===skill.id);if(!rows.length)return null;const compared=repeatedProgress(rows);const fails=rows.filter(a=>!a.correct);const counts=new Map<string,number>();for(const a of fails)counts.set(a.error_type??'UNKNOWN',(counts.get(a.error_type??'UNKNOWN')??0)+1);const dominant=[...counts].sort((a,b)=>b[1]-a[1])[0];return <details className="progress-skill" key={skill.id}><summary><strong>{skill.name}</strong><span>{compared?compared.delta>0?`Mejoró ${compared.delta} puntos`:compared.delta<0?`${Math.abs(compared.delta)} puntos menos`:'Se mantiene':'Falta otro día comparable'}</span></summary><div className="progress-detail">{compared&&<p>{compared.previousDate}: {compared.previous}% ({compared.previousCount} intentos) → {compared.date}: {compared.current}% ({compared.currentCount}). Comparamos los mismos niveles: {compared.levels.join(', ')}. Las pistas pueden cambiar entre días.</p>}<p>{dominant?`Conviene reforzar: ${errors[dominant[0]]??dominant[0]}. ${dominant[1]} de ${fails.length} respuestas por revisar.`:'No hay errores registrados en esta habilidad.'}</p><h3>Ayudas y ejercicios concretos</h3>{rows.filter(a=>a.hint_level>0||!a.correct).slice(0,8).map(a=><div className="attempt-example" key={a.id}><small>{new Date(a.created_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})} · Nivel {a.level-1} · {a.hint_level?`Pista ${a.hint_level}`:'Sin pista'}</small><p>{a.prompt_text}</p>{!a.correct&&<p>Respondió {a.given_answer}. Esperado: {a.expected_answer}.</p>}</div>)}</div></details>})}
 <details className="hint-history"><summary>Cuándo pidió pistas</summary>{hints.length?hints.map(e=><p key={e.id}>{new Date(e.occurred_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})} · {skills.find(s=>s.id===e.skill_id)?.name??'Práctica'} · pregunta {Number(e.properties.step??0)+1} · pista {String(e.properties.hint_level)}</p>):<p>Aún no hay solicitudes recientes fuera de las pruebas. Las ayudas guardadas con respuestas aparecen en cada habilidad.</p>}</details></section>;
}
