"use client";
import {useState} from 'react';
import {eventLabels,usageSummary,type UsageEvent} from '@/lib/engine/telemetry';
import type {integrationHealth} from '@/lib/data/telemetry';
import {track} from '@/components/telemetry/client';
export function UsagePanel({events,available,truncated,health}:{events:UsageEvent[];available:boolean;truncated:boolean;health:Awaited<ReturnType<typeof integrationHealth>>}){
 const [actor,setActor]=useState('shared_refuge');const [includeTests,setIncludeTests]=useState(false);
 const selected=events.filter(e=>e.actor_kind===actor&&(includeTests||!e.is_test));
 const summary=usageSummary(includeTests?selected.map(e=>({...e,is_test:false})):selected,actor);
 const features=[['care_feed','Comedor'],['care_play','Jugar'],['care_clean','Limpiar'],['view_cats','Colección de gatos'],['view_skills','Mapa de habilidades'],['image_zoom_in','Zoom de imágenes']];
 return <section className="usage-panel" id="usage">
  <div className="studio-heading"><div><h2>Qué usa. Dónde necesita compañía.</h2><p>Últimos 14 días · uso dentro de la app. Las señales orientan; una pausa no significa dificultad ni falta de interés.</p></div><button className="secondary" onClick={()=>{track('control_used',{control:'usage_export'});const blob=new Blob([JSON.stringify(selected,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='refugio-uso.json';a.click();URL.revokeObjectURL(url);}}>Descargar registros</button></div>
  <details className="usage-health"><summary>Estado de las conexiones IA</summary>{health?<><p>Últimos 7 días · {health.total} solicitudes{health.limited?' más recientes':''}. Incluye consultas del profe y comprobaciones técnicas; no mide el rendimiento de Laura.</p><div className="usage-totals">{[[health.completed,'completadas'],[health.failed,'interrumpidas'],[health.pending,'en curso'],[health.unconfirmed,'sin cierre confirmado']].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><p>{health.medianSeconds===null?'Aún no hay tiempos de respuesta medidos.':`Respuesta típica: ${health.medianSeconds} s (mediana de ${health.measured} conversaciones medidas).`} Las pistas del ejercicio siguen disponibles si Numa no responde.</p></>:<p>No pudimos consultar el estado ahora. Recarga para reintentar.</p>}</details>
  {!available ? <p role="status">El registro no está disponible ahora. La práctica sigue funcionando. Recarga para reintentar.</p> : <>
  <div className="usage-filters"><label>Origen<select value={actor} onChange={e=>setActor(e.target.value)}><option value="shared_refuge">Refugio compartido</option><option value="tutor">Profe autenticado</option><option value="visitor">Pantalla de acceso</option></select></label><label><input type="checkbox" checked={includeTests} onChange={e=>setIncludeTests(e.target.checked)}/> Incluir pruebas y vista previa del profe</label></div>
  <p className="usage-note">El enlace de Laura es compartido: no verifica quién lo está usando. No registramos pantallas, contraseñas, teclas ni navegación externa. Los eventos detallados se conservan 90 días; respuestas y conversaciones mantienen su historial.</p>
  {truncated&&<p role="status">Esta vista contiene una muestra limitada de los eventos recientes. Los conteos son de esta muestra.</p>}
  <div className="usage-totals">{[[summary.visits,'visitas observadas'],[summary.activeMinutes,'minutos activos'],[summary.counts.mission_started??0,'misiones iniciadas'],[summary.counts.mission_completed??0,'misiones completadas'],[summary.counts.mission_left??0,'salidas durante misión'],[summary.counts.save_failed??0,'guardados por reintentar']].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>
  {!selected.length?<p>Aún no hay uso registrado en este origen. Los datos aparecerán al explorar y practicar.</p>:<p>Primer evento de esta muestra: {new Date(summary.firstEvent!).toLocaleString('es-CO')}.</p>}
  <div className="usage-columns"><div><h3>Ayudas y señales de esfuerzo</h3>{(['hint_requested','solution_viewed','input_invalid','answer_edited','coach_opened','coach_requested','coach_replied','coach_failed','file_opened','generation_completed','runtime_error'] as const).map(name=><div className="usage-row" key={name}><span>{eventLabels[name]}</span><b>{summary.counts[name]??0}</b></div>)}</div><div><h3>Funciones exploradas</h3>{features.map(([key,label])=><div className="usage-row" key={key}><span>{label}</span><b>{summary.controls[key]??'Sin uso observado'}</b></div>)}<p className="usage-note">«Sin uso observado» no significa que no le guste. Numa combina estas señales con respuestas y pistas reales.</p></div></div>
  <details className="usage-timeline"><summary>Ver los últimos eventos ({Math.min(100,selected.length)})</summary><ol>{selected.slice(0,100).map(e=><li key={e.id}><time>{new Date(e.occurred_at).toLocaleString('es-CO')}</time><strong>{eventLabels[e.event_name]??e.event_name}</strong><span>{Object.entries(e.properties).map(([k,v])=>`${k}: ${v}`).join(' · ')}</span></li>)}</ol></details>
  </>}
 </section>;
}
